allowBuilds:
  better-sqlite3: true
  electron: true
  electron-winstaller: true

onlyBuiltDependencies:
  - better-sqlite3
  - electron
  - electron-winstaller
  - esbuild

overrides:
  '@sveltejs/kit@<=2.57.0': '>=2.57.1'
  '@sveltejs/kit@>=2.38.0 <=2.60.0': '>=2.60.1'
  '@xmldom/xmldom@<0.8.13': '>=0.8.13'
  axios@>=1.0.0 <1.15.0: '>=1.15.0'
  brace-expansion@>=5.0.0 <5.0.6: '>=5.0.6'
  cookie@<0.7.0: '>=0.7.0'
  devalue@>=5.6.3 <=5.8.0: '>=5.8.1'
  follow-redirects@<=1.15.11: '>=1.16.0'
  qs@>=6.11.1 <=6.15.1: '>=6.15.2'
  svelte@<=5.55.6: '>=5.55.7'
  svelte@>=5.46.0 <=5.55.6: '>=5.55.7'
  svelte@>=5.51.5 <=5.55.6: '>=5.55.7'
  tmp@<0.2.6: '>=0.2.6'
